
%define where the images are
imageDir = {'/orchestra/groups/lccb-receptors/Rich/control_0125/movie1/',...
    '/orchestra/groups/lccb-receptors/Rich/control_0125/movie2/',...
    '/orchestra/groups/lccb-receptors/Rich/control_0125/movie3/',...
    '/orchestra/groups/lccb-receptors/Rich/control_0125/movie4/',...
    '/orchestra/groups/lccb-receptors/Rich/control_0125/movie5/',...
    '/orchestra/groups/lccb-receptors/Rich/control_0125/movie6/',...
    '/orchestra/groups/lccb-receptors/Rich/control_0125/movie7/',...
    '/orchestra/groups/lccb-receptors/Rich/control_0125/movie8/',...
    '/orchestra/groups/lccb-receptors/Rich/control_0125/movie9/',...
    '/orchestra/groups/lccb-receptors/Rich/control_0125/movie10/',...
    '/orchestra/groups/lccb-receptors/Rich/control_0125/movie11/'};

%define the name of the detection file
detectionFileName = {'detection1.mat',...
    'detection1.mat',...
    'detection1.mat',...
    'detection1.mat',...
    'detection1.mat',...
    'detection1.mat',...
    'detection1.mat',...
    'detection1.mat',...
    'detection1.mat',...
    'detection1.mat',...
    'detection1.mat',...
    'detection1.mat'};

%define the name of the first image in a series
imageName = {'0125_jasp_001_0001.tif',...
    '0125_jasp_002_0001.tif',...
    '0125_jasp_003_0001.tif',...
    '0125_jasp_004_0001.tif',...
    '0125_jasp_005_0001.tif',...
    '0125_jasp_006_0001.tif',...
    '0125_jasp_007_0001.tif',...
    '0125_jasp_008_0001.tif',...
    '0125_jasp_009_0001.tif',...
    '0125_jasp_010_0001.tif',...
    '0125_jasp_011_0001.tif'};

%calculate number of movies
numMovies = length(imageDir);

%initialize feature density and its standard deviation
featDensity = NaN(numMovies,2);

%go over all movies
for iMovie = 1 : numMovies
    
    %open the detection file
    load(fullfile(imageDir{iMovie},detectionFileName{iMovie}));
    
    %open the image
    image = imread(fullfile(imageDir{iMovie},imageName{iMovie}));
    
    %find number of nonzero pixels
    cellArea = length(find(image~=0));
    
    %get number of features in each frame
    numFeat = NaN(size(movieInfo));
    for iFrame = 1 : size(movieInfo)
        numFeat(iFrame,1) = size(movieInfo(iFrame).xCoord,1);
    end
    
    %calculate mean and std of feature density
    featDensity(iMovie,:) = [mean(numFeat) std(numFeat)] / cellArea;
    
end