
%% define batch job locations

%image locations
imageDir = {...
    '/home/kj35/orchestra/groups/lccb-maki/Telomeres/2D/delta50_3_R3D_D3D_PRJ/crop1/',...
    '/home/kj35/orchestra/groups/lccb-maki/Telomeres/2D/delta50_3_R3D_D3D_PRJ/crop2/',...
    '/home/kj35/orchestra/groups/lccb-maki/Telomeres/2D/delta50_3_R3D_D3D_PRJ/crop3/',...
    '/home/kj35/orchestra/groups/lccb-maki/Telomeres/2D/shRNA2_1_R3D_D3D_PRJ/crop1/',...
    '/home/kj35/orchestra/groups/lccb-maki/Telomeres/2D/shRNA2_1_R3D_D3D_PRJ/crop2/',...
    '/home/kj35/orchestra/groups/lccb-maki/Telomeres/2D/WT01_5_R3D_D3D_PRJ/crop1/',...
    '/home/kj35/orchestra/groups/lccb-maki/Telomeres/2D/WT01_5_R3D_D3D_PRJ/crop2/',...
    };

%file name bases
filenameBase = {...
    'crop_delta50_3_R3D_D3D_PRJ_T',...
    'crop_delta50_3_R3D_D3D_PRJ_T',...
    'crop_delta50_3_R3D_D3D_PRJ_T',...
    'crop_shRNA2_1_R3D_D3D_PRJ_T',...
    'crop_shRNA2_1_R3D_D3D_PRJ_T',...
    'crop_WT01_5_R3D_D3D_PRJ_T',...
    'crop_WT01_5_R3D_D3D_PRJ_T',...
    };

%directory for saving results
saveResDir = {...
    '/home/kj35/orchestra/groups/lccb-maki/Telomeres/2D/delta50_3_R3D_D3D_PRJ/crop1/',...
    '/home/kj35/orchestra/groups/lccb-maki/Telomeres/2D/delta50_3_R3D_D3D_PRJ/crop2/',...
    '/home/kj35/orchestra/groups/lccb-maki/Telomeres/2D/delta50_3_R3D_D3D_PRJ/crop3/',...
    '/home/kj35/orchestra/groups/lccb-maki/Telomeres/2D/shRNA2_1_R3D_D3D_PRJ/crop1/',...
    '/home/kj35/orchestra/groups/lccb-maki/Telomeres/2D/shRNA2_1_R3D_D3D_PRJ/crop2/',...
    '/home/kj35/orchestra/groups/lccb-maki/Telomeres/2D/WT01_5_R3D_D3D_PRJ/crop1/',...
    '/home/kj35/orchestra/groups/lccb-maki/Telomeres/2D/WT01_5_R3D_D3D_PRJ/crop2/',...
    };

%% calculate number of movies
numMovies = length(filenameBase);

for iMovie = 1 : numMovies
    
    try
        
        %display movie number
        disp(['Movie ' num2str(iMovie) ' / ' num2str(numMovies) ' ...'])
        
        %% movie information
        movieParam.imageDir = imageDir{iMovie}; %directory where images are
        movieParam.filenameBase = filenameBase{iMovie}; %image file name base
        movieParam.firstImageNum = 1; %number of first image in movie
        movieParam.lastImageNum = 41; %number of last image in movie
        movieParam.digits4Enum = 2; %number of digits used for frame enumeration (1-4).
        
        %% detection parameters
        detectionParam.psfSigma = 1; %point spread function sigma (in pixels)
        detectionParam.testAlpha = struct('alphaR',0.01,'alphaA',0.01,'alphaD',0.01,'alphaF',0); %alpha-values for detection statistical tests
        detectionParam.visual = 0; %1 to see image with detected features, 0 otherwise
        detectionParam.doMMF = 1; %1 if mixture-model fitting, 0 otherwise
        detectionParam.bitDepth = 16; %Camera bit depth
        detectionParam.alphaLocMax = 0.05; %alpha-value for initial detection of local maxima
        detectionParam.numSigmaIter = 10; %maximum number of iterations for PSF sigma estimation
        detectionParam.integWindow = 0; %number of frames before and after a frame for time integration
        
        %% save results
        saveResults.dir = saveResDir{iMovie}; %directory where to save input and output
        saveResults.filename = 'detectionAll1.mat'; %name of file where input and output are saved
        % saveResults = 0;
        
        %% run the detection function
        [movieInfo,exceptions,localMaxima,background,psfSigma] = ...
            detectSubResFeatures2D_StandAlone(movieParam,detectionParam,saveResults);
        
    catch %#ok<CTCH>
        disp(['Movie ' num2str(iMovie) ' failed!']);
    end
    
end
