
%% define batch job locations

%image locations
imageDir = {...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_06/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_07/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_08/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_09/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_10/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_11/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_12/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_13/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_14/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_15/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_16/CD36every3rd/',...
    };

%file name bases
filenameBase = {...
    'mov_06_new_',...
    'mov_07_new_',...
    'mov_08_new_',...
    'mov_09_new_',...
    'mov_10_new_',...
    'mov_11_new_',...
    'mov_12_new_',...
    'mov_13_new_',...
    'mov_14_new_',...
    'mov_15_new_',...
    'mov_16_new_',...
    };

%directory for saving results
saveResDir = {...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_06/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_07/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_08/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_09/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_10/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_11/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_12/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_13/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_14/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_15/CD36every3rd/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36TubulinKJ_3/mov_16/CD36every3rd/',...
    };

% %background image locations
% bgImageDir = {...
%     '/home/kj35/orchestra/groups/lccb-receptors/Galbraiths/data/alphaVandCellEdge/110114/Cs2_CHO02/Cs2_CHO02B/bgAlphaV/',...
%     };
%
% %background file name bases
% bgFilenameBase = {...
%     'crop_110114_Cs2_CHO02B_',...
%     };

%% calculate number of movies
numMovies = length(filenameBase);

for iMovie = 1 : numMovies
    
    try
        
        %display movie number
        disp(['Movie ' num2str(iMovie) ' / ' num2str(numMovies) ' ...'])
        
        %% movie information
        movieParam.imageDir = imageDir{iMovie}; %directory where images are
        movieParam.filenameBase = filenameBase{iMovie}; %image file name base
        movieParam.firstImageNum = 1; %number of first image in movie
        movieParam.lastImageNum = 148; %number of last image in movie
        movieParam.digits4Enum = 4; %number of digits used for frame enumeration (1-4).
        
        %% detection parameters
        detectionParam.psfSigma = 1.6; %point spread function sigma (in pixels)
        detectionParam.testAlpha = struct('alphaR',0.005,'alphaA',0.005,'alphaD',0.005,'alphaF',0); %alpha-values for detection statistical tests
        detectionParam.visual = 0; %1 to see image with detected features, 0 otherwise
        detectionParam.doMMF = 1; %1 if mixture-model fitting, 0 otherwise
        detectionParam.bitDepth = 16; %Camera bit depth
        detectionParam.alphaLocMax = 0.01; %alpha-value for initial detection of local maxima
        detectionParam.numSigmaIter = 10; %maximum number of iterations for PSF sigma estimation
        detectionParam.integWindow = 0; %number of frames before and after a frame for time integration
        
        %         %background info ...
        %         background.imageDir = bgImageDir{iMovie};
        %         background.filenameBase = bgFilenameBase{iMovie};
        %         background.alphaLocMaxAbs = 0.01;
        %         detectionParam.background = background;
        
        %% save results
        saveResults.dir = saveResDir{iMovie}; %directory where to save input and output
        saveResults.filename = 'detectionAll1.mat'; %name of file where input and output are saved
        % saveResults = 0;
        
        %% run the detection function
        [movieInfo,exceptions,localMaxima,background,psfSigma] = ...
            detectSubResFeatures2D_StandAlone(movieParam,detectionParam,saveResults);
        
    catch %#ok<CTCH>
        disp(['Movie ' num2str(iMovie) ' failed!']);
    end
    
end
