
%% define batch job locations

%track locations
trackDir = {...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36Tubulin_1/analysis/tracking/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36Tubulin_1/analysis/tracking/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36Tubulin_1/analysis/tracking/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36Tubulin_1/analysis/tracking/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36Tubulin_1/analysis/tracking/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36Tubulin_1/analysis/tracking/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36Tubulin_1/analysis/tracking/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Nico/2011-02-28_CD36Tubulin/CD36Tubulin_1/analysis/tracking/',...
   };

%track file names
trackFile = {...
    'mov_01_tracks.mat',...
    'mov_02_tracks.mat',...
    'mov_03_tracks.mat',...
    'mov_05_tracks.mat',...
    'mov_07_tracks.mat',...
    'mov_08_tracks.mat',...
    'mov_09_tracks.mat',...
    'mov_10_tracks.mat',...
    };

%movie names
movieName = {...
    'mov01',...
    'mov02',...
    'mov03',...
    'mov05',...
    'mov07',...
    'mov08',...
    'mov09',...
    'mov10',...
    };

%calculate number of movies
numMovies1 = length(trackDir);
numMovies2 = length(trackFile);
numMovies3 = length(movieName);
if any([numMovies1-numMovies2 numMovies2-numMovies3 numMovies3-numMovies1]) ~= 0
    disp('Number of entries in movieInfoDir, movieInfoFile and saveResDir does not match!')
    return
end

%% collect movies

%generate structure for putting all tracks together
trackData = repmat(struct('name',[],'tracks',[]),numMovies1,1);

for iMovie = 1 : numMovies1
    
    %read tracks
    load(fullfile(trackDir{iMovie},trackFile{iMovie}));
    
    %collect tracks and movie name
    trackData(iMovie).name = movieName{iMovie};
    trackData(iMovie).tracks = tracksFinal;
    
end
