
%% define batch job locations

% %track locations
% trackDir = {...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_bleb_02/analysis/',...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_bleb_03/analysis/',...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_bleb_05/analysis/',...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_bleb_07/analysis/',...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_bleb_09/analysis/',...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_clnb_02/analysis/',...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_clnb_04/analysis/',...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_clnb_06/analysis/',...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_clnb_08/analysis/',...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_clnb_10/analysis/',...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_clnb_12/analysis/',...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_noco_02/analysis/',...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_noco_04/analysis/',...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_noco_06/analysis/',...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_noco_08/analysis/',...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_noco_11/analysis/',...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_noco_15/analysis/',...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_noco_17/analysis/',...
%     '/orchestra/groups/lccb-receptors/Hiro/071229_many/control/con_noco_21/analysis/',...
%     };

%track file names
trackFile = {...
    'tracks100329Detection4_4.mat',...
    'tracks100329Detection4_4.mat',...
    'tracks100329Detection4_4.mat',...
    'tracks100329Detection4_4.mat',...
    'tracks100329Detection4_4.mat',...
    'tracks100329Detection4_4.mat',...
    'tracks100329Detection4_4.mat',...
    'tracks100329Detection4_4.mat',...
    'tracks100329Detection4_4.mat',...
    'tracks100329Detection4_4.mat',...
    'tracks100329Detection4_4.mat',...
    'tracks100329Detection4_4.mat',...
    };

%movie names
movieName = {...
    '0124_movie1',...
    '0124_movie2',...
    '0124_movie3',...
    '0124_movie4',...
    '0124_movie5',...
    '0124_movie6',...
    '0124_movie7',...
    '0124_movie8',...
    '0124_movie9',...
    '0124_movie10',...
    '0124_movie11',...
    '0124_movie12',...
    };

%calculate number of movies
numMovies1 = length(trackDir);
numMovies2 = length(trackFile);
numMovies3 = length(movieName);
if any([numMovies1-numMovies2 numMovies2-numMovies3 numMovies3-numMovies1]) ~= 0
    disp('Number of entries in movieInfoDir, movieInfoFile and saveResDir does not match!')
    return
end

%% collect movies

%generate structure for putting all tracks together
trackData = repmat(struct('name',[],'tracks',[]),numMovies1,1);

for iMovie = 1 : numMovies1
    
    %read tracks
    load(fullfile(trackDir{iMovie},trackFile{iMovie}));
    
    %collect tracks and movie name
    trackData(iMovie).name = movieName{iMovie};
    trackData(iMovie).tracks = tracksFinal;
    
end
