classdef ExternalSegmentationProcess < SegmentationProcess
    % A concrete class for importing segmentation generated by 3d party
    % software
    
    methods(Access = public)
        
        function obj = ExternalSegmentationProcess(owner, varargin)
            % Input check
            ip = inputParser;
            ip.addRequired('owner',@(x) isa(x,'MovieData'));
            ip.addOptional('outputDir',owner.outputDirectory_,@ischar);
            ip.addOptional('funParams',[],@isstruct);
            ip.parse(owner,varargin{:});
            
            super_args{1} = owner;
            super_args{2} = ExternalSegmentationProcess.getName();
            super_args{3} = @importExternalSegmentation;
            if isempty(ip.Results.funParams)
                super_args{4} = ExternalSegmentationProcess.getDefaultParams(...
                    owner, ip.Results.outputDir);
            else
                super_args{4} = ip.Results.funParams;
            end
            
            obj = obj@SegmentationProcess(super_args{:});
        end
    end
    methods (Static)
        
        function name = getName()
            name = 'External Segmentation';
        end
        
        function funParams = getDefaultParams(owner,varargin)
            % Input check
            ip=inputParser;
            ip.addRequired('owner',@(x) isa(x,'MovieData'));
            ip.addOptional('outputDir',owner.outputDirectory_,@ischar);
            ip.parse(owner, varargin{:})
            outputDir=ip.Results.outputDir;
            
            % Set default parameters
            funParams.OutputDirectory = [outputDir  filesep 'externalSegmentation'];
            funParams.InputData = cell(numel(owner.channels_), 1);
        end
    end
end
