
%% define batch job locations

%track locations
trackDir = {...
    '/home/kj35/files/LCCB/receptors/endoCells/AnindyaChanda/20110822_Monodispersion/Blank/Field1/Analysis/',...
    '/home/kj35/files/LCCB/receptors/endoCells/AnindyaChanda/20110822_Monodispersion/Blank/Field1/Analysis/',...
    '/home/kj35/files/LCCB/receptors/endoCells/AnindyaChanda/20110822_Monodispersion/10_7/Field1/Analysis/',...
    '/home/kj35/files/LCCB/receptors/endoCells/AnindyaChanda/20110822_Monodispersion/10_7/Field2/Analysis/',...
    '/home/kj35/files/LCCB/receptors/endoCells/AnindyaChanda/20110822_Monodispersion/10_6/Field1/Analysis/',...
    '/home/kj35/files/LCCB/receptors/endoCells/AnindyaChanda/20110822_Monodispersion/10_6/Field2/Analysis/',...
    '/home/kj35/files/LCCB/receptors/endoCells/AnindyaChanda/20110822_Monodispersion/10_5/Field1/Analysis/',...
    '/home/kj35/files/LCCB/receptors/endoCells/AnindyaChanda/20110822_Monodispersion/10_5/Field2/Analysis/',...
   };

%track file names
trackFile = {...
    'tracksDetectionAll2.mat',...
    'tracksDetectionAll2.mat',...
    'tracksDetectionAll2.mat',...
    'tracksDetectionAll2.mat',...
    'tracksDetectionAll2.mat',...
    'tracksDetectionAll2.mat',...
    'tracksDetectionAll2.mat',...
    'tracksDetectionAll2.mat',...
    };

%movie names
movieName = {...
    'blank_1',...
    'blank_2',...
    '10-7_1',...
    '10-7_2',...
    '10-6_1',...
    '10-6_2',...
    '10-5_1',...
    '10-5_2',...
    };

%calculate number of movies
numMovies1 = length(trackDir);
numMovies2 = length(trackFile);
numMovies3 = length(movieName);
if any([numMovies1-numMovies2 numMovies2-numMovies3 numMovies3-numMovies1]) ~= 0
    disp('Number of entries in movieInfoDir, movieInfoFile and saveResDir does not match!')
    return
end

%% collect movies

%generate structure for putting all tracks together
trackData = repmat(struct('name',[],'tracks',[]),numMovies1,1);

for iMovie = 1 : numMovies1
    
    %read tracks
    load(fullfile(trackDir{iMovie},trackFile{iMovie}));
    
    %collect tracks and movie name
    trackData(iMovie).name = movieName{iMovie};
    trackData(iMovie).tracks = tracksFinal;
    
end
