
%% define batch job locations

%track locations
trackDir = {...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/control02/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/control04/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/control06/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/control08/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/control10/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/control12/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/control14/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/control16/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/control18/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/control20/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/control22/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/control24/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/control26/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/control28/',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/control30/',...
   };

%track file names
trackFile = {...
    'tracks1DetectionAll4.mat',...
    'tracks1DetectionAll4.mat',...
    'tracks1DetectionAll4.mat',...
    'tracks1DetectionAll4.mat',...
    'tracks1DetectionAll4.mat',...
    'tracks1DetectionAll4.mat',...
    'tracks1DetectionAll4.mat',...
    'tracks1DetectionAll4.mat',...
    'tracks1DetectionAll4.mat',...
    'tracks1DetectionAll4.mat',...
    'tracks1DetectionAll4.mat',...
    'tracks1DetectionAll4.mat',...
    'tracks1DetectionAll4.mat',...
    'tracks1DetectionAll4.mat',...
    'tracks1DetectionAll4.mat',...
    };

%movie names
movieName = {...
    'control02',...
    'control04',...
    'control06',...
    'control08',...
    'control10',...
    'control12',...
    'control14',...
    'control16',...
    'control18',...
    'control20',...
    'control22',...
    'control24',...
    'control26',...
    'control28',...
    'control30',...
    };

%calculate number of movies
numMovies1 = length(trackDir);
numMovies2 = length(trackFile);
numMovies3 = length(movieName);
if any([numMovies1-numMovies2 numMovies2-numMovies3 numMovies3-numMovies1]) ~= 0
    disp('Number of entries in movieInfoDir, movieInfoFile and saveResDir does not match!')
    return
end

%% collect movies

%generate structure for putting all tracks together
trackData = repmat(struct('name',[],'tracks',[]),numMovies1,1);

for iMovie = 1 : numMovies1
    
    %read tracks
    load(fullfile(trackDir{iMovie},trackFile{iMovie}));
    
    %collect tracks and movie name
    trackData(iMovie).name = movieName{iMovie};
    trackData(iMovie).tracks = tracksFinal;
    
end
